#pragma once

// ALL TOKEN TYPES FOR LUNARIS LANGUAGE
// Token used for lexing and parsing where each token has a type and a value
typedef enum TokenType {
    // Single-character tokens
    TOKEN_LEFT_PAREN, TOKEN_RIGHT_PAREN, TOKEN_LEFT_BRACE, TOKEN_RIGHT_BRACE,
    TOKEN_COMMA, TOKEN_DOT, TOKEN_MINUS, TOKEN_PLUS, TOKEN_SEMICOLON, TOKEN_SLASH, TOKEN_STAR, TOKEN_PERCENT,
    TOKEN_COLON, TOKEN_DOUBLE_COLON, TOKEN_QUESTION_MARK,

    // One or two character tokens
    TOKEN_NOT,        TOKEN_NOT_EQUAL,
    TOKEN_EQUAL,      TOKEN_EQUAL_EQUAL,
    TOKEN_GREATER,    TOKEN_GREATER_EQUAL,
    TOKEN_LESS,       TOKEN_LESS_EQUAL,

    // Logical operators
    TOKEN_AND,        TOKEN_AND_AND,
    TOKEN_OR,         TOKEN_OR_OR,

    // Type keywords (for parsing, not static type system)
    TOKEN_TYPE_INT, TOKEN_TYPE_BOOL, TOKEN_TYPE_FLOAT, TOKEN_TYPE_CHAR, TOKEN_TYPE_STRING, TOKEN_TYPE_VOID, TOKEN_TYPE_NONE,

    // Keywords
    TOKEN_CLASS, TOKEN_ELSE, TOKEN_FALSE, TOKEN_FUNCTION, TOKEN_FOR, TOKEN_IF, TOKEN_NIL,
    TOKEN_RETURN, TOKEN_SUPER, TOKEN_THIS, TOKEN_TRUE, TOKEN_CONST, TOKEN_LET, TOKEN_WHILE,
    TOKEN_CONTINUE, TOKEN_BREAK, TOKEN_ELIF, TOKEN_IMPORT, TOKEN_SWITCH, TOKEN_CASE, TOKEN_DEFAULT,

    // Modifiers
    TOKEN_MUTABLE, TOKEN_IMMUTABLE, TOKEN_STATIC, TOKEN_PUBLIC, TOKEN_PRIVATE,

    // Literals
    TOKEN_IDENTIFIER, TOKEN_STRING, TOKEN_INT, TOKEN_FLOAT, TOKEN_CHAR, TOKEN_BOOL,TOKEN_VOID,

    // End of file
    TOKEN_EOF
} TokenType;
// No alias needed; TokenType is now the enum name